DROP TABLE IF EXISTS position;
CREATE TABLE position(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_name VARCHAR NOT NULL
);
INSERT INTO position(position_name)
  VALUES
    ('Junior'),
    ('Senior'),
    ('Management'),
    ('Director');

DROP TABLE IF EXISTS users ;
CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR NOT NULL,
  user_name VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL,
  user_position INT NOT NULL REFERENCES position(id),
  reports_to INT REFERENCES users(id),
  isAdmin BOOLEAN DEFAULT FALSE
  );