DROP TABLE IF EXISTS orgs;
CREATE TABLE orgs (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar NOT null UNIQUE,
  org_name varchar NOT NULL,
  admin int null REFERENCES users(id) ON DELETE CASCADE,
  parent int REFERENCES orgs(id) DEFAULT NUll
);
ALTER TABLE users
  ADD COLUMN 
    org int REFERENCES orgs(id) ON DELETE SET NULL;
  DROP TABLE IF EXISTS teams;
  ALTER Table users
  Add COLUMN
    team INT NULL REFERENCES orgs(id)  ON DELETE SET NULL;