CREATE TABLE lvl(
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lvl_name varchar NOT NULL
);
INSERT INTO lvl (lvl_name)
  VALUES
    ('Global'),
    ('Department'),
    ('Team'),
    ('Personal');