CREATE TABLE notices(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar NOT NULL,
  content TEXT,
  org int NOT NULL REFERENCES orgs(id) ON DELETE SET NULL,
  created_by INT REFERENCES users(id) ON DELETE SET NUll,
  create_on TIMESTAMPTZ DEFAULT now()

);