
CREATE TABLE notices(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar NOT NULL,
  content TEXT,
  level INT NOT NULL REFERENCES lvl(id), 
  org int NOT NULL REFERENCES orgs(id) ON DELETE SET NULL,
  created_by INT REFERENCES users(id) ON DELETE SET NUll,
  created_on TIMESTAMPTZ DEFAULT now()
  --need expiration
 
);